# Generated by Django 5.1.5 on 2025-01-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='fornecdor',
            new_name='fornecedor',
        ),
    ]
